purpose: read in the validation analyses and make readable tables for them

# set-up

In [34]:
import pandas as pd
import os
import numpy as np

In [5]:
os.chdir('/tscc/projects/ps-palmer/brittany/SUD_cross_species/')

In [2]:
label_h='ext_top500'
label_r='loco_final_cf_FDR'
interactome_name='PCNet2.0'
cut_single=1.5
cut_comb=3

# RAT GWAS CATALOG

In [10]:
source='RGD'

In [11]:
rgd_cat={
'seedh':pd.read_csv(f'validation_output/{source}_enr_seed_genes-{label_h}_{interactome_name}_enr.csv'),
'seedr':pd.read_csv(f'validation_output/{source}_enr_seed_genes-{label_r}_{interactome_name}_enr.csv'),
'coloc_net':pd.read_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_NPS-{cut_single}-{cut_comb}_{interactome_name}_enr.csv'),
'netr':pd.read_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_rat_specific_{interactome_name}_enr.csv'),
'neth':pd.read_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_human_specific_{interactome_name}_enr.csv')
}

In [12]:
cutoff=0.05/len(set(rgd_cat['coloc_net']['trait']))

In [14]:
for k in rgd_cat.keys():
    rgd_cat[k]=rgd_cat[k].drop_duplicates()
    print(k)
    df=rgd_cat[k]
    display(df[df.p_intersect<cutoff])

seedh

Empty DataFrame
Columns: [trait, parent_trait, community_genes, n_community_genes, odds_ratio, log_se_or, p_intersect, depth]
Index: []

seedr

Empty DataFrame
Columns: [trait, parent_trait, community_genes, n_community_genes, odds_ratio, log_se_or, p_intersect, depth]
Index: []

coloc_net

,trait,parent_trait,community_genes,n_community_genes,odds_ratio,log_se_or,p_intersect,depth
1,behavior/neurological phenotype,mammalian phenotype,"{'GAD1', 'HCN1', 'SCN1A', 'CRHR1', 'CACNA1E', ...",8,21.447619,0.797684,0.000016,0
85,abnormal behavior,behavior/neurological phenotype,"{'GAD1', 'HCN1', 'SCN1A', 'CRHR1', 'CACNA1E', ...",8,21.692308,0.797740,0.000015,1
217,seizures,abnormal nervous system physiology,"{'SCN1A', 'CACNA1E', 'GAD1', 'HCN1'}",4,36.444444,0.708184,0.000040,2
452,seizures,abnormal behavior,"{'SCN1A', 'CACNA1E', 'GAD1', 'HCN1'}",4,36.444444,0.708184,0.000040,2

netr

Empty DataFrame
Columns: [trait, parent_trait, community_genes, n_community_genes, odds_ratio, log_se_or, p_intersect, depth]
Index: []

neth

,trait,parent_trait,community_genes,n_community_genes,odds_ratio,log_se_or,p_intersect,depth
26331,abnormal cocaine consumption,abnormal behavioral response to xenobiotic,"{'BDNF', 'CDH13', 'GRIN2A', 'GRIA2'}",4,28.130435,0.738257,0.000126,3
60820,abnormal cocaine self-administration,abnormal cocaine consumption,"{'BDNF', 'CDH13', 'GRIN2A', 'GRIA2'}",4,28.130435,0.738257,0.000126,4

In [15]:
k='coloc_net'
df=rgd_cat[k]
display(df[df.p_intersect<cutoff])

,trait,parent_trait,community_genes,n_community_genes,odds_ratio,log_se_or,p_intersect,depth
1,behavior/neurological phenotype,mammalian phenotype,"{'GAD1', 'HCN1', 'SCN1A', 'CRHR1', 'CACNA1E', ...",8,21.447619,0.797684,0.000016,0
85,abnormal behavior,behavior/neurological phenotype,"{'GAD1', 'HCN1', 'SCN1A', 'CRHR1', 'CACNA1E', ...",8,21.692308,0.797740,0.000015,1
217,seizures,abnormal nervous system physiology,"{'SCN1A', 'CACNA1E', 'GAD1', 'HCN1'}",4,36.444444,0.708184,0.000040,2
452,seizures,abnormal behavior,"{'SCN1A', 'CACNA1E', 'GAD1', 'HCN1'}",4,36.444444,0.708184,0.000040,2

In [ ]:
for k in rgd_cat.keys():
    print(k)
    df=rgd_cat[k]
    display(df[df.p_intersect<cutoff].loc[df[df.p_intersect<cutoff].groupby('depth')['p_intersect'].idxmin()])

# MGI

In [76]:
source='MGI'
mgi_cat={
'seedh':pd.read_csv(f'validation_output/{source}_enr_seed_genes-{label_h}_{interactome_name}_enr.csv'),
'seedr':pd.read_csv(f'validation_output/{source}_enr_seed_genes-{label_r}_{interactome_name}_enr.csv'),
'coloc_net':pd.read_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_NPS-{cut_single}-{cut_comb}_{interactome_name}_enr.csv'),
'netr':pd.read_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_rat_specific_{interactome_name}_enr.csv'),
'neth':pd.read_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_human_specific_{interactome_name}_enr.csv')
}

In [77]:
cutoff=0.05/len(set(mgi_cat['coloc_net']['trait']))

In [74]:
for k in mgi_cat.keys():
    print(k)
    df=mgi_cat[k]
    display(df[df.p_intersect<cutoff].loc[df[df.p_intersect<cutoff].groupby('depth')['p_intersect'].idxmin()])

seedh

Empty DataFrame
Columns: [trait, parent_trait, community_genes, n_community_genes, odds_ratio, log_se_or, p_intersect, depth]
Index: []

seedr

Empty DataFrame
Columns: [trait, parent_trait, community_genes, n_community_genes, odds_ratio, log_se_or, p_intersect, depth]
Index: []

coloc_net

,trait,parent_trait,community_genes,n_community_genes,odds_ratio,log_se_or,p_intersect,depth
1,behavior/neurological phenotype,mammalian phenotype,"{'GAD1', 'HCN1', 'SCN1A', 'CRHR1', 'CACNA1E', ...",8,21.447619,0.797684,0.000016,0
85,abnormal behavior,behavior/neurological phenotype,"{'GAD1', 'HCN1', 'SCN1A', 'CRHR1', 'CACNA1E', ...",8,21.692308,0.797740,0.000015,1
217,seizures,abnormal nervous system physiology,"{'SCN1A', 'CACNA1E', 'GAD1', 'HCN1'}",4,36.444444,0.708184,0.000040,2

netr

Empty DataFrame
Columns: [trait, parent_trait, community_genes, n_community_genes, odds_ratio, log_se_or, p_intersect, depth]
Index: []

neth

,trait,parent_trait,community_genes,n_community_genes,odds_ratio,log_se_or,p_intersect,depth
26331,abnormal cocaine consumption,abnormal behavioral response to xenobiotic,"{'BDNF', 'CDH13', 'GRIN2A', 'GRIA2'}",4,28.130435,0.738257,0.000126,3
60820,abnormal cocaine self-administration,abnormal cocaine consumption,"{'BDNF', 'CDH13', 'GRIN2A', 'GRIA2'}",4,28.130435,0.738257,0.000126,4

# GO Enrichment

In [85]:
source='go'
go={'coloc_net':pd.read_csv('network_analysis/GO_enr_colocalized-network_ext_top500_loco_final_cf_FDR.csv'),
'neth':pd.read_csv('network_analysis/GO_enr_human-only-network_ext_top500_loco_final_cf_FDR.csv'),
'seedh':pd.read_csv('network_analysis/GO_enr_human-seed_ext_top500_loco_final_cf_FDR.csv'),
'netr':pd.read_csv('network_analysis/GO_enr_rat-only-network_ext_top500_loco_final_cf_FDR.csv'),
'seedr':pd.read_csv('network_analysis/GO_enr_rat-seed_ext_top500_loco_final_cf_FDR.csv')}

In [77]:
cutoff=0.05/len(set(mgi_cat['coloc_net']['trait']))

In [100]:
t1='seedr'
t2='coloc_net'
print(f'traits shared between {t1} and {t2}:\n')
print(set(go[t1]['name']).intersection(go[t2]['name']))

traits shared between seedr and coloc_net:

{'regulation of system process', 'calcium ion transmembrane import into cytosol', 'transport', 'calcium ion transmembrane transport', 'calcium ion transport', 'behavior', 'nervous system development', 'monoatomic ion transport', 'inorganic cation transmembrane transport', 'metal ion transport', 'system development', 'monoatomic cation transmembrane transport', 'inorganic ion transmembrane transport', 'establishment of localization', 'animal organ development', 'anatomical structure morphogenesis', 'multicellular organism development', 'monoatomic ion transmembrane transport', 'transmembrane transport', 'cell surface receptor signaling pathway', 'regulation of multicellular organismal process'}

In [108]:
t2='seedr'
t3='coloc_net'
t1='seedh'
print(f'traits not shared between between {t1} and {t2} + {t3}:\n')
l=list(set(go[t1]['name']).difference(go[t2]['name']).difference(go[t3]['name']))
print('\n'.join(l))

traits not shared between between seedh and seedr + coloc_net:

cell motility
protein modification by small protein conjugation or removal
negative regulation of neuron apoptotic process
regulation of regulatory T cell differentiation
positive regulation of macromolecule metabolic process
cell-cell adhesion via plasma-membrane adhesion molecules
positive regulation of multicellular organismal process
muscle cell apoptotic process
post-translational protein modification
neuron projection guidance
immune response-regulating signaling pathway
regulation of anatomical structure morphogenesis
regulation of cell adhesion
cell death
positive regulation of cell adhesion
synaptic membrane adhesion
negative regulation of catabolic process
cell-cell adhesion
tissue regeneration
immune response-regulating cell surface receptor signaling pathway
positive regulation of metabolic process
regulatory T cell differentiation
water transport
programmed cell death
mitotic nuclear division
T cell receptor signaling pathway
immune response-activating signaling pathway
renal water transport
phosphatidylinositol 3-kinase/protein kinase B signal transduction
semaphorin-plexin signaling pathway
neuron recognition
negative regulation of cellular component organization
positive regulation of nucleobase-containing compound metabolic process
immune response-activating cell surface receptor signaling pathway
protein modification process
regulation of multicellular organismal development
regulation of smooth muscle cell apoptotic process
negative regulation of muscle cell apoptotic process
positive regulation of response to stimulus
antigen receptor-mediated signaling pathway
hindbrain radial glia guided cell migration
axon guidance
apoptotic process
multicellular organismal-level water homeostasis
negative regulation of smooth muscle cell apoptotic process
macromolecule modification
negative regulation of motor neuron apoptotic process
tissue development
cell migration
regulation of muscle cell apoptotic process
positive regulation of macromolecule biosynthetic process
regulation of axonogenesis
positive regulation of DNA-templated transcription
regulation of phosphatidylinositol 3-kinase/protein kinase B signal transduction
cell adhesion
regulation of chemotaxis
protein modification by small protein conjugation
regulation of signal transduction
regulation of modification of postsynaptic structure
intracellular signal transduction
smooth muscle cell apoptotic process
positive regulation of biosynthetic process
regulation of response to stimulus
fluid transport
regulation of catabolic process
positive regulation of axonogenesis
positive regulation of DNA metabolic process

In [104]:
t1='seedr'
t2='coloc_net'
t3='seedh'
print(f'traits not shared between between {t1} and {t2} + {t3}:\n')
l=list(set(go[t1]['name']).difference(go[t2]['name']).difference(go[t3]['name']))

traits not shared between between seedr and coloc_net + seedh:

intracellular monoatomic ion homeostasis
regulation of blood circulation
cornea development in camera-type eye
inorganic ion homeostasis
regulation of heart contraction
homeostatic process
cell-cell adhesion involved in gastrulation
regulation of protein phosphorylation
calcium ion homeostasis
regulation of cell cycle
heart contraction
regulation of cell-cell adhesion involved in gastrulation
protein phosphorylation
intracellular calcium ion homeostasis
phosphorylation
regulation of protein metabolic process
response to wounding
positive regulation of phosphorylation
coagulation
intracellular monoatomic cation homeostasis
monoatomic cation homeostasis
blood coagulation
regulation of skeletal muscle tissue regeneration
regulation of phosphorylation
B cell apoptotic process
nitric oxide biosynthetic process
phosphate-containing compound metabolic process
phosphorus metabolic process
negative regulation of heterotypic cell-cell adhesion
regulation of heart rate
monoatomic ion homeostasis
hemostasis

# GWAS Catalog (EFO Structure)

In [70]:
source='GWAS-CAT-EFO'

In [71]:
gwas_cat={
'seedh':pd.read_csv(f'validation_output/{source}_enr_seed_genes-{label_h}_{interactome_name}_enr.csv'),
'seedr':pd.read_csv(f'validation_output/{source}_enr_seed_genes-{label_r}_{interactome_name}_enr.csv'),
'coloc_net':pd.read_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_NPS-{cut_single}-{cut_comb}_{interactome_name}_enr.csv'),
}
#'netr':pd.read_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_rat_specific_{interactome_name}_enr.csv'),
#'neth':pd.read_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_human_specific_{interactome_name}_enr.csv')

In [72]:
parents=['disease', 'measurement', 'biological_process', 'experimental factor']
par_children={}
for p in parents:
    par_children[p]=list(pd.read_csv(f'validation_datasets/efo_parent_children_terms_{p}.txt',header=None)[0])

In [73]:
parents=['disease', 'measurement', 'biological_process', 'experimental factor']
par_children_names={}
for p in parents:
    par_children_names[p]=list(pd.read_csv(f'validation_datasets/efo_parent_children_terms_names_{p}.txt',sep='\t',header=None)[0])

In [58]:
'''par_children['disease']=set(par_children['disease']).difference(list(par_children['measurement'])+list(par_children['biological_process']))
par_children['biological_process']=set(par_children['biological_process']).difference(par_children['measurement'])
par_children['experimental factor']=set(par_children['experimental factor']).difference(list(par_children['disease'])+list(par_children['biological_process'])+list(par_children['measurement']))'''

In [75]:
for p in parents:
    df=gwas_cat[k][gwas_cat[k].trait.isin(par_children_names[p])]
    print(p)
    for k in ['coloc_net']:
        print(k)
        display(df[df.p_intersect<cutoff].loc[df[df.p_intersect<cutoff].groupby('depth')['p_intersect'].idxmin()])

disease
coloc_net

,trait,parent_trait,community_genes,n_community_genes,odds_ratio,log_se_or,p_intersect,depth,seed_h,seed_r,n_seed_h,n_seed_r,n_seed,ngenes,trait_ID
554,psychiatric disorder,disease,"{'GNPDA2', 'DAOA', 'GABRB3', 'SHTN1', 'MARCHF7...",185,2.478569,0.141870,1.154290e-11,1,set(),set(),0,0,0,16954,MONDO:0002025
2686,substance-related disorder,psychiatric disorder,"{'TRAIP', 'MDGA2', 'UTRN', 'TULP4', 'GABRB3', ...",58,3.906747,0.152370,2.643175e-15,2,{'TRAIP'},{'TRAIP'},1,1,2,2277,MONDO:0002494
4425,substance abuse,substance-related disorder,"{'TRAIP', 'MDGA2', 'UTRN', 'TULP4', 'GABRA2', ...",36,6.523318,0.186382,1.452875e-16,3,{'TRAIP'},{'TRAIP'},1,1,2,806,MONDO:0002491
4207,psychosis,cognitive disorder,"{'DAOA', 'GRM1', 'LYPD6B', 'RNF39', 'GRIA1', '...",82,2.893596,0.135940,2.940097e-13,4,set(),set(),0,0,0,4452,EFO:0005407
2687,substance-related disorder,psychiatric disorder,"{'TRAIP', 'MDGA2', 'UTRN', 'TULP4', 'GABRB3', ...",58,3.906747,0.152370,2.643175e-15,5,{'TRAIP'},{'TRAIP'},1,1,2,2277,MONDO:0002494

measurement
coloc_net

,trait,parent_trait,community_genes,n_community_genes,odds_ratio,log_se_or,p_intersect,depth,seed_h,seed_r,n_seed_h,n_seed_r,n_seed,ngenes,trait_ID
417,educational attainment,measurement,"{'GNPDA2', 'GABRB3', 'SHTN1', 'PAX4', 'GRIA1',...",101,3.103410,0.129739,1.300548e-16,1,set(),set(),0,0,0,5376,EFO:0011015
2889,self reported educational attainment,educational attainment,"{'GNPDA2', 'GABRB3', 'SHTN1', 'PAX4', 'GRIA1',...",99,3.096418,0.130214,2.229487e-16,2,set(),set(),0,0,0,5244,EFO:0004784
418,educational attainment,measurement,"{'GNPDA2', 'GABRB3', 'SHTN1', 'PAX4', 'GRIA1',...",101,3.103410,0.129739,1.300548e-16,3,set(),set(),0,0,0,5376,EFO:0011015
2890,self reported educational attainment,educational attainment,"{'GNPDA2', 'GABRB3', 'SHTN1', 'PAX4', 'GRIA1',...",99,3.096418,0.130214,2.229487e-16,4,set(),set(),0,0,0,5244,EFO:0004784
5117,smoking status measurement,smoking behavior trait,"{'TULP4', 'ADAT1', 'UTRN', 'SHTN1', 'DPYSL2', ...",48,3.490251,0.163285,1.223848e-11,5,set(),set(),0,0,0,1905,EFO:0006527

biological_process
coloc_net

,trait,parent_trait,community_genes,n_community_genes,odds_ratio,log_se_or,p_intersect,depth,seed_h,seed_r,n_seed_h,n_seed_r,n_seed,ngenes,trait_ID
1,biological_process,exploratory factor,"{'GNPDA2', 'DAOA', 'GABRB3', 'KCNMB1', 'SHTN1'...",225,1.955339,0.198199,1.790803e-04,0,set(),set(),0,0,0,27374,GO:0008150
462,mental process,biological_process,"{'GNPDA2', 'GABRB3', 'SHTN1', 'PAX4', 'RNF39',...",90,2.601486,0.132687,7.582651e-12,1,set(),set(),0,0,0,5537,EFO:0004323
2654,behavior,multicellular organismal process,"{'GNPDA2', 'SHTN1', 'PLAG1', 'XRN2', 'GRM1', '...",109,3.173348,0.128218,7.589830e-18,2,set(),set(),0,0,0,6511,GO:0007610
4537,smoking initiation,behavior,"{'GNPDA2', 'MDGA2', 'ADAT1', 'UTRN', 'TULP4', ...",68,3.703590,0.144157,3.287688e-16,3,set(),set(),0,0,0,2826,EFO:0005670
2655,behavior,multicellular organismal process,"{'GNPDA2', 'SHTN1', 'PLAG1', 'XRN2', 'GRM1', '...",109,3.173348,0.128218,7.589830e-18,4,set(),set(),0,0,0,6511,GO:0007610
4538,smoking initiation,behavior,"{'GNPDA2', 'MDGA2', 'ADAT1', 'UTRN', 'TULP4', ...",68,3.703590,0.144157,3.287688e-16,5,set(),set(),0,0,0,2826,EFO:0005670

experimental factor
coloc_net

,trait,parent_trait,community_genes,n_community_genes,odds_ratio,log_se_or,p_intersect,depth,seed_h,seed_r,n_seed_h,n_seed_r,n_seed,ngenes,trait_ID
1,biological_process,exploratory factor,"{'GNPDA2', 'DAOA', 'GABRB3', 'KCNMB1', 'SHTN1'...",225,1.955339,0.198199,1.790803e-04,0,set(),set(),0,0,0,27374,GO:0008150
417,educational attainment,measurement,"{'GNPDA2', 'GABRB3', 'SHTN1', 'PAX4', 'GRIA1',...",101,3.103410,0.129739,1.300548e-16,1,set(),set(),0,0,0,5376,EFO:0011015
2654,behavior,multicellular organismal process,"{'GNPDA2', 'SHTN1', 'PLAG1', 'XRN2', 'GRM1', '...",109,3.173348,0.128218,7.589830e-18,2,set(),set(),0,0,0,6511,GO:0007610
418,educational attainment,measurement,"{'GNPDA2', 'GABRB3', 'SHTN1', 'PAX4', 'GRIA1',...",101,3.103410,0.129739,1.300548e-16,3,set(),set(),0,0,0,5376,EFO:0011015
2655,behavior,multicellular organismal process,"{'GNPDA2', 'SHTN1', 'PLAG1', 'XRN2', 'GRM1', '...",109,3.173348,0.128218,7.589830e-18,4,set(),set(),0,0,0,6511,GO:0007610
4538,smoking initiation,behavior,"{'GNPDA2', 'MDGA2', 'ADAT1', 'UTRN', 'TULP4', ...",68,3.703590,0.144157,3.287688e-16,5,set(),set(),0,0,0,2826,EFO:0005670

In [93]:
for p in parents:
    #print(p)
    for k in ['coloc_net']:
        df=gwas_cat[k][gwas_cat[k].trait_ID.isin(par_children[p])]
        #print(k)
        df['-log10(p)']=-np.log10(df['p_intersect'])
        x=df[df.p_intersect<cutoff].loc[df[df.p_intersect<cutoff].groupby('depth')['p_intersect'].idxmin()][['trait','n_community_genes','odds_ratio','-log10(p)','depth','trait_ID']]
        x.to_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_NPS-{cut_single}-{cut_comb}_{interactome_name}_enr_top_terms_per_depth_{p}.csv')

/tmp/ipykernel_193375/493095494.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/493095494.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/493095494.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/493095494.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])

In [95]:
df

,trait,parent_trait,community_genes,odds_ratio,log_se_or,p_intersect,depth,ngenes,trait_ID,-log10(p)
7,cardiovascular disease,disease,"{'TFAP2B', 'SFMBT1', 'RBFOX1', 'FAF1', 'XKR6',...",2.086240,0.094413,1.303900e-15,1,13754,EFO:0000319,14.884756
8,cardiovascular disease,disease,"{'TFAP2B', 'SFMBT1', 'RBFOX1', 'FAF1', 'XKR6',...",2.086240,0.094413,1.303900e-15,4,13754,EFO:0000319,14.884756
9,cardiovascular disease,Homo sapiens,"{'TFAP2B', 'SFMBT1', 'RBFOX1', 'FAF1', 'XKR6',...",2.086240,0.094413,1.303900e-15,5,13754,EFO:0000319,14.884756
10,digestive system disease,disease,"{'OLA1', 'TFAP2B', 'SFMBT1', 'RBFOX1', 'XKR6',...",2.212307,0.096514,1.597290e-17,1,14255,EFO:0000405,16.796616
11,digestive system disease,disease,"{'OLA1', 'TFAP2B', 'SFMBT1', 'RBFOX1', 'XKR6',...",2.212307,0.096514,1.597290e-17,4,14255,EFO:0000405,16.796616
...,...,...,...,...,...,...,...,...,...,...
8487,partial epilepsy,epilepsy,"{'SMARCA5', 'PTPRD', 'GABRA2', 'BCL11A', 'PCDH...",6.825437,0.415618,1.749698e-04,5,65,EFO:0004263,3.757037
8488,electroclinical syndrome,epilepsy,"{'BCL11A', 'GABRA2'}",11.602564,0.817771,1.962477e-02,5,11,MONDO:0000411,1.707195
8489,epilepsy syndrome,epilepsy,"{'BCL11A', 'GABRA2'}",9.944477,0.803081,2.476887e-02,5,13,MONDO:0015650,1.606094
8494,leiomyoma,Benign Smooth Muscle Neoplasm,"{'SLK', 'CTNNA2', 'NKAIN2', 'TENM2', 'IGF1', '...",2.341718,0.314786,1.093300e-02,5,281,MONDO:0001572,1.961261
8496,Herpes simplex infection,Herpesviridae infectious disease,"{'AKT3', 'HLA-A', 'TBC1D5', 'TRIM27', 'RBFOX1'}",4.063373,0.474711,1.077115e-02,5,95,EFO:1002022,1.967738

In [106]:
y

,trait,odds_ratio,-log10(p),depth,trait_ID,grandparent
2368,functional impairment measurement,37.923197,3.610725,2,EFO:0005412,disease
4153,substance abuse,2.646575,3.993428,3,MONDO:0002491,disease
2370,functional impairment measurement,37.923197,3.610725,4,EFO:0005412,disease
3574,noise-induced hearing loss,50.567398,3.847420,5,EFO:1001254,disease
290,sulfate measurement,21.190852,4.848247,1,EFO:0007864,measurement
776,nucleoside diphosphate kinase B measurement,151.721003,4.533684,2,EFO:0020615,measurement
291,sulfate measurement,21.190852,4.848247,3,EFO:0007864,measurement
777,nucleoside diphosphate kinase B measurement,151.721003,4.533684,4,EFO:0020615,measurement
779,nucleoside diphosphate kinase B measurement,151.721003,4.533684,5,EFO:0020615,measurement
776,nucleoside diphosphate kinase B measurement,151.721003,4.533684,2,EFO:0020615,biological_process
3572,noise-induced hearing loss,50.567398,3.847420,3,EFO:1001254,biological_process
777,nucleoside diphosphate kinase B measurement,151.721003,4.533684,4,EFO:0020615,biological_process
779,nucleoside diphosphate kinase B measurement,151.721003,4.533684,5,EFO:0020615,biological_process

In [108]:
y=pd.DataFrame()
for p in parents:
    #print(p)
    for k in ['seedh']:
        df=gwas_cat[k][gwas_cat[k].trait_ID.isin(par_children[p])]
        #print(k)
        df['-log10(p)']=-np.log10(df['p_intersect'])
        x=df[df.p_intersect<cutoff].loc[df[df.p_intersect<cutoff].groupby('depth')['p_intersect'].idxmin()][['trait','odds_ratio','-log10(p)','depth','trait_ID']]
        x['grandparent']=p
        #display(x)
        y=y.append(x)
y.to_csv(f'validation_output/{source}_enr_seed_genes-{label_h}_{interactome_name}_enr_top_terms_per_depth_comb.csv')

/tmp/ipykernel_193375/895404174.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/895404174.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y=y.append(x)
/tmp/ipykernel_193375/895404174.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/895404174.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y=y.append(x)
/tmp/ipykernel_193375/895404174.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/895404174.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y=y.append(x)
/tmp/ipykernel_193375/895404174.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/895404174.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y=y.append(x)

In [ ]:
parents=['disease', 'measurement', 'biological_process', 'experimental factor']

In [116]:
y=pd.DataFrame()

for p in parents:
    df=gwas_cat[k][gwas_cat[k].trait_ID.isin(par_children[p])]
    #print(p)
    for k in ['coloc_net']:
        #print(k)
        df['-log10(p)']=-np.log10(df['p_intersect'])
        x=df[df.p_intersect<cutoff].loc[df[df.p_intersect<cutoff].groupby('depth')['p_intersect'].idxmin()][['trait','odds_ratio','-log10(p)','depth','trait_ID']]
        x['grandparent']=p
        y=y.append(x)
y.to_csv(f'validation_output/{source}_enr_network-{label_h}-{label_r}_NPS-{cut_single}-{cut_comb}_{interactome_name}_enr_top_terms_per_depth_comb.csv')

/tmp/ipykernel_193375/1122376842.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/1122376842.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y=y.append(x)
/tmp/ipykernel_193375/1122376842.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/1122376842.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y=y.append(x)
/tmp/ipykernel_193375/1122376842.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/1122376842.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y=y.append(x)
/tmp/ipykernel_193375/1122376842.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['-log10(p)']=-np.log10(df['p_intersect'])
/tmp/ipykernel_193375/1122376842.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y=y.append(x)

In [118]:
y[y.depth!=0]

,trait,odds_ratio,-log10(p),depth,trait_ID,grandparent
554,psychiatric disorder,2.478569,10.937685,1,MONDO:0002025,disease
2686,substance-related disorder,3.906747,14.577874,2,MONDO:0002494,disease
4425,substance abuse,6.523318,15.837772,3,MONDO:0002491,disease
4207,psychosis,2.893596,12.531638,4,EFO:0005407,disease
2687,substance-related disorder,3.906747,14.577874,5,MONDO:0002494,disease
417,educational attainment,3.103410,15.885873,1,EFO:0011015,measurement
2889,self reported educational attainment,3.096418,15.651795,2,EFO:0004784,measurement
418,educational attainment,3.103410,15.885873,3,EFO:0011015,measurement
2890,self reported educational attainment,3.096418,15.651795,4,EFO:0004784,measurement
5117,smoking status measurement,3.490251,10.912272,5,EFO:0006527,measurement
462,mental process,2.601486,11.120179,1,EFO:0004323,biological_process
2654,behavior,3.173348,17.119768,2,GO:0007610,biological_process
4537,smoking initiation,3.703590,15.483109,3,EFO:0005670,biological_process
2655,behavior,3.173348,17.119768,4,GO:0007610,biological_process
4538,smoking initiation,3.703590,15.483109,5,EFO:0005670,biological_process
599,process,1.942843,3.683902,1,BFO:0000015,experimental factor
2581,quality,2.118925,6.202242,2,BFO:0000019,experimental factor
5089,self-reported trait,5.198877,7.811536,3,EFO:0009799,experimental factor
6052,"comparative body size at age 10, self-reported",5.255495,7.884241,4,EFO:0009819,experimental factor
6374,Abnormality of the nervous system,2.382807,10.868112,5,HP:0000707,experimental factor

In [64]:
for p in ['measurement']:
    
    df=gwas_cat[k][gwas_cat[k].trait_ID.isin(par_children[p])]
    #print(p)
    for k in ['coloc_net']:
        #print(k)
        df=gwas_cat[k]
        df['-log10(p)']=-np.log10(df['p_intersect'])
        display(df[df.p_intersect<cutoff].loc[df[df.p_intersect<cutoff].groupby('depth')['p_intersect'].idxmin()][['trait','n_community_genes','n_seed','odds_ratio','-log10(p)','depth','trait_ID']])

,trait,n_community_genes,n_seed,odds_ratio,-log10(p),depth,trait_ID
1,biological_process,225,0,1.955339,3.746952,0,GO:0008150
417,educational attainment,101,0,3.103410,15.885873,1,EFO:0011015
2654,behavior,109,0,3.173348,17.119768,2,GO:0007610
418,educational attainment,101,0,3.103410,15.885873,3,EFO:0011015
2655,behavior,109,0,3.173348,17.119768,4,GO:0007610
4538,smoking initiation,68,0,3.703590,15.483109,5,EFO:0005670